name: Release to Main (Recursive)
run-name: Releasing dx-runtime and submodules to main (Triggered by ${{ github.event.client_payload.parent_sha }})

on:
  repository_dispatch:
    types:
      - release-to-main

permissions: write-all

env:
  OWNER: DEEPX-AI

jobs:
  release:
    runs-on:
      - self-hosted
      - sdk
    timeout-minutes: 15
    steps:
      - name: Clean Workspace
        run: |
          sudo rm -rf ${{ github.workspace }}
          mkdir -p ${{ github.workspace }}

      - name: Checkout Main Branch
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GC_DCI_TOKEN }}
          fetch-depth: 0

      - name: Fetch Staging Branch
        run: git fetch origin staging

      - name: Get Last Staging Commit Message for dx-runtime
        id: get_dx_runtime_staging_message
        run: |
          LAST_STAGING_COMMIT_MESSAGE=$(git log -1 --pretty=%B origin/staging)
          echo "LAST_STAGING_COMMIT_MESSAGE=$LAST_STAGING_COMMIT_MESSAGE" >> $GITHUB_ENV

      - name: Check dx-runtime Diff (Staging vs Main)
        id: check_dx_runtime_diff
        run: |
          if git diff --quiet main origin/staging; then
            echo "::notice::No differences in dx-runtime main vs staging. Skipping direct merge."
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "::notice::Differences found in dx-runtime. Proceeding with direct merge."
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Merge dx-runtime Staging to Main (Squash)
        if: steps.check_dx_runtime_diff.outputs.has_changes == 'true'
        run: |
          git merge --squash origin/staging -m "${{ env.LAST_STAGING_COMMIT_MESSAGE }}"
          git commit -m "${{ env.LAST_STAGING_COMMIT_MESSAGE }}"
          git push origin main

      - name: Recreate Staging Branch for dx-runtime from Main
        if: steps.check_dx_runtime_diff.outputs.has_changes == 'true'
        run: |
          echo "Deleting remote origin/staging branch for dx-runtime..."
          git push origin --delete staging || true
          
          echo "Checking out main branch and pulling latest for dx-runtime..."
          git checkout main
          git pull origin main
          
          echo "Creating new staging branch from main for dx-runtime..."
          git checkout -b staging
          
          echo "Pushing new staging branch to origin for dx-runtime..."
          git push -u origin staging

      - name: Get Current dx-runtime Main SHA
        id: get_dx_runtime_sha
        run: echo "dx_runtime_sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Dispatch to dx_app
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GC_DCI_TOKEN }}
          repository: ${{ env.OWNER }}/dx_app
          event-type: merge-staging-to-main
          client-payload: |
            {
              "repo_name": "dx_app",
              "parent_owner": "DEEPX-AI",
              "parent_repo": "dx-runtime",
              "parent_sha": "${{ steps.get_dx_runtime_sha.outputs.dx_runtime_sha }}",
              "parent_ref": "main"
            }

      - name: Dispatch to dx_rt
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GC_DCI_TOKEN }}
          repository: ${{ env.OWNER }}/dx_rt
          event-type: merge-staging-to-main
          client-payload: |
            {
              "repo_name": "dx_rt",
              "parent_owner": "DEEPX-AI",
              "parent_repo": "dx-runtime",
              "parent_sha": "${{ steps.get_dx_runtime_sha.outputs.dx_runtime_sha }}",
              "parent_ref": "main"
            }

      - name: Dispatch to dx_rt_npu_linux_driver
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GC_DCI_TOKEN }}
          repository: ${{ env.OWNER }}/dx_rt_npu_linux_driver
          event-type: merge-staging-to-main
          client-payload: |
            {
              "repo_name": "dx_rt_npu_linux_driver",
              "parent_owner": "DEEPX-AI",
              "parent_repo": "dx-runtime",
              "parent_sha": "${{ steps.get_dx_runtime_sha.outputs.dx_runtime_sha }}",
              "parent_ref": "main"
            }

      - name: Dispatch to dx_fw
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GC_DCI_TOKEN }}
          repository: ${{ env.OWNER }}/dx_fw
          event-type: merge-staging-to-main
          client-payload: |
            {
              "repo_name": "dx_fw",
              "parent_owner": "DEEPX-AI",
              "parent_repo": "dx-runtime",
              "parent_sha": "${{ steps.get_dx_runtime_sha.outputs.dx_runtime_sha }}",
              "parent_ref": "main"
            }

      - name: Dispatch to dx_stream
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GC_DCI_TOKEN }}
          repository: ${{ env.OWNER }}/dx_stream
          event-type: merge-staging-to-main
          client-payload: |
            {
              "repo_name": "dx_stream",
              "parent_owner": "DEEPX-AI",
              "parent_repo": "dx-runtime",
              "parent_sha": "${{ steps.get_dx_runtime_sha.outputs.dx_runtime_sha }}",
              "parent_ref": "main"
            }
